# basic configs
[common]
dataset_name = "radar"
input_length = 9
total_length = 29
cpu_workers = 0
crop_size = 384
batch_size = 1
generator_base_channels = 32
device = "cuda:0"
save_original_data = true
pred_length = 20
gen_decoder_input_channels = 320
# the path of the toch model weights file (.pt)"
weights_path = "for example: /home/nowcastnet/data/checkpoints/rewritten_model.pt"

# specific configs for normal case
[normal]
# the path to the dataset
dataset_path = "for example: /home/nowcastnet/data/dataset/mrms/raw/figure/"
image_height = 512
image_width = 512
case_type = "normal"

# specific configs for large case
[large]
# the path to the dataset
dataset_path = "for example: /home/nowcastnet/data/dataset/mrms/raw/large_figure/"
image_width = 1024
case_type = "large"
