# basic configs
[common]
dataset_path = "for example: /home/nowcastnet/data/dataset/mrms/raw/figure/"
dataset_name = "radar"
input_length = 9
total_length = 29
cpu_workers = 0
crop_size = 384
batch_size = 1
weights_path = "for example: /home/nowcastnet/data/checkpoints/rewritten_model.pt"
seed = 42
save_original_data = true
pred_length = 20
generator_base_channels = 32

# specific configs for normal case
[normal]
image_height = 512
image_width = 512
# path to store the inference result
results_path = "for example: /home/nowcastnet/results/inference/normal"
# path to the onnx model
graph_path = "for example: /home/nowcastnet/data/checkpoints/rewritten_model_512.onnx"
# path to store the inference log
path_to_log = "for example: logs/inference_normal.log"

# specific configs for large case
[large]
image_height = 1024
image_width = 1024
# path to store the inference result
results_path = "for example: /home/nowcastnet/results/inference/large"
# path to the onnx model
graph_path = "for example: /home/nowcastnet/data/checkpoints/rewritten_model_1024.onnx"
# path to store the inference log
path_to_log = "for example: logs/inference_large.log"
